# Generated by Django 5.1.6 on 2025-02-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rated_movies',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='saved_movies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
