# Generated by Django 5.1.6 on 2025-02-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_id_alter_movie_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielist',
            name='movies',
        ),
        migrations.AddField(
            model_name='movielist',
            name='movie_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
