# Generated by Django 5.1.6 on 2025-02-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movielist_id_alter_movielist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
